package com.datamodel;
// Generated Apr 2, 2017 5:14:33 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements Serializable {


     private int commentid;
     private Customer customer;
     private Product product;
     private String title;
     private String body;
     private Serializable commenttime;
     private float rating;

    public Comments() {
    }

	
    public Comments(int commentid, Customer customer, Product product, String body, Serializable commenttime) {
        this.commentid = commentid;
        this.customer = customer;
        this.product = product;
        this.body = body;
        this.commenttime = commenttime;
    }
    public Comments(int commentid, Customer customer, Product product, String title, String body, Serializable commenttime) {
       this.commentid = commentid;
       this.customer = customer;
       this.product = product;
       this.title = title;
       this.body = body;
       this.commenttime = commenttime;
    }
   
    public int getCommentid() {
        return this.commentid;
    }
    
    public void setCommentid(int commentid) {
        this.commentid = commentid;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    public Serializable getCommenttime() {
        return commenttime;
    }

    public void setCommenttime(Serializable commenttime) {
        this.commenttime = commenttime;
    }
    
    public float getRating() {
        return rating;
    }

    public void setRating(float rating) {
        this.rating = rating;
    }




}


