package com.datamodel;
// Generated Apr 2, 2017 5:14:33 PM by Hibernate Tools 4.3.1



/**
 * Wishlist generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {

     private int id;
     private String name;
     private String email;
     private String comments;

    public Feedback() {
    }

    public Feedback(String name, String email, String comments) {
       this.name = name;
       this.email = email;
       this.comments = comments;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
   




}


