package com.datamodel;
// Generated Apr 2, 2017 5:14:33 PM by Hibernate Tools 4.3.1



/**
 * Wishlist generated by hbm2java
 */
public class Wishlist  implements java.io.Serializable {


     private int wishlistid;
     private Customer customer;
     private Product product;

    public Wishlist() {
    }

    public Wishlist(int wishlistid, Customer customer, Product product) {
       this.wishlistid = wishlistid;
       this.customer = customer;
       this.product = product;
    }
   
    public int getWishlistid() {
        return this.wishlistid;
    }
    
    public void setWishlistid(int wishlistid) {
        this.wishlistid = wishlistid;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


